### ISSUE TITLE
Dunst only showing bold text properly

### ISSUE THREAD

**Issue by anonaii** [NerdyPepper/scientifica#37]
Everything that isn't in bold is shown as a unicode box
![slopsh-32](https://user-images.githubusercontent.com/43378896/77835728-966df400-711d-11ea-8914-706cdab67d5f.png)
(Note, the box before "Chats" is expected, it's an emoji)
![slopsh-33](https://user-images.githubusercontent.com/43378896/77836106-4002b480-7121-11ea-8162-b7a94a4d54be.png)

Here's my dunstrc;
https://gist.github.com/anonaii/a0115432fb3e8b3c51f28654d184532a

**Comment by NerdyPepper** [comment]
on line 89, the font face name should be `scientifica` with a small `s`. but i'm not sure if that's really an issue.

these rectangular placeholders would usually occur if the character is not a part of the font, but i think this is caused by pango removing support for non opentype bitmap font formats.

some things you could try:
 - use the `otb` font files instead of `bdf` if you aren't already doing so
 - run `fc-cache --really-force -v`

if none of that works, could you please share the following:
 - the output of `fc-list | grep sci`
 - the version of `pango` you have installed

**Comment by anonaii** [comment]
I tried both Scientifica, and scientifica, neither of which changed anything.
Here's my fc-list;
![slopsh-36](https://user-images.githubusercontent.com/43378896/77856625-092eac00-71be-11ea-89b0-7f2b0e71caac.png)
and pango;
![slopsh-37](https://user-images.githubusercontent.com/43378896/77856642-1d72a900-71be-11ea-9c25-2d9a89cda761.png)

**Comment by anonaii** [comment]
For further information I'm using both the bdf files from the git repo (~/.local/share/fonts) and the AUR package otb-scientifica (/usr/share/fonts/misc/)

**Comment by NerdyPepper** [comment]
could you remove the `bdf`s from `~/.local/share/fonts`, run `fc-cache -fv` and restart `dunst` and tell me if that works? its possible that `bdf` edition is shadowing the `otb` one.

**Comment by anonaii** [comment]
Aha! That was exactly it, after removing the bdf's dunst is properly showing non-bold text. Thanks for the help man!

**Comment by NerdyPepper** [comment]
Cheers :^)
