### ISSUE TITLE
Making the font bigger ?

### ISSUE THREAD

**Issue by Kapuche** [NerdyPepper/scientifica#44]
Hi everybody,

the font looks great, but it's so tiny, I must be at 3cm to be able to see it on my terminal, can someone help me ? I tried in the tweak application to make it bigger, but no differences.

**Comment by NerdyPepper** [comment]
Since, [v2.0](https://github.com/NerdyPepper/scientifica/releases), scientifica ships with scalable TTF variants, which are rasterized at 11px and its multiples. If that doesn't suit your use case, you might want to try [curie](https://github.com/NerdyPepper/curie), scientifica's upscaled sister font.

Bitmap fonts aren't the [same size](https://peppe.rs/posts/font_size_fallacies/) on all displays, they are pixel perfect, and vary as pixel sizes vary (pixels aren't the same size on all displays either!).
