### ISSUE TITLE
Is this possible on Windows?

### ISSUE THREAD

**Issue by 2hands10fingers** [NerdyPepper/scientifica#52]
Can this font work well on Windows or would you need to make a port for it?

**Comment by NerdyPepper** [comment]
This font should work as expected on most windows applications, you can head over to the releases page, download and extract the `tar` file, and install the `TTF` variants. I used to release `.fon` file formats as well, but it became a little tedious to maintain.

Just play around with the font size on your application till it renders out the rasterized variant (should be between 7px and 11px). Every integer multiple of that size should also be rasterized. Other sizes will appear blurry, due to aliasing, hinting etc.

If everything goes well, consider [submitting a screenshot of your setup](https://github.com/NerdyPepper/scientifica/issues/33)! If not, feel free to reopen this issue.
